### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: models; No such file or directory

### ISSUE THREAD

**Issue by JeetShah10** [aisecure/Characterizing-Audio-Adversarial-Examples-using-Temporal-Dependency#2]
While running TDeval.py file,
saver.restore(sess, "models/session_dump") this line giving me an error of models; No such file or directory

Traceback (most recent call last):
  File "TDeval.py", line 91, in <module>
    D = Decoder(sess, maxlen)
  File "TDeval.py", line 41, in __init__
    saver.restore(sess, "models/session_dump")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1536, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_management.py", line 364, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: models; No such file or directory

Can anyone help me with how can I resolve this error?

Thanks in advance.

**Comment by ruby11dog** [comment]
Is this issue solved? I got the same problem.

**Comment by ruby11dog** [comment]
Hi, you should create a file named session_dump and put DeepSpeechv0.4.1 model in the file.
